{{- if .Values.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "storm.fullname" . }}-supervisor
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}-supervisor"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: "{{ .Values.name }}-supervisor"
    spec:
      containers:
        - name: {{ template "name" . }}-{{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["storm", "supervisor"]
          resources:
{{ toYaml .Values.supervisor_resources | indent 12 }}
          env:
            - name: STORM_HOSTNAME_FROM_IP
              value: "true"
            - name: ZOOKEEPER_SERVERS
              value: "{{ .Release.Name }}-zookeeper"
            - name: STORM_ZOOKEEPER_PORT
              value: "2181"
            - name: NIMBUS_SEEDS
              value: "{{ template "storm.fullname" . }}-nimbus"
            - name: SUPERVISOR_SLOTS_PORTS
              value: {{ .Values.supervisor_ports | join "," | quote }}
{{- end}}
