mysql_init:
  image:
    repository: monasca/mysql-init
    tag: 1.4.0
    pullPolicy: IfNotPresent
  disable_remote_root: false

influx_init:
  image:
    repository: monasca/influxdb-init
    tag: latest
    pullPolicy: IfNotPresent

grafana_init:
  image:
    repository: monasca/grafana-init
    tag: latest
    pullPolicy: Always
  log_level: INFO
  username: mini-mon
  password: password
  datasource:
    type: monasca
    access_mode: proxy

influxdb:
  image:
    repo: "influxdb"
    tag: "1.1"
    pullPolicy: IfNotPresent
  service:
    type: NodePort
  persistence:
    enabled: false
    storageClass: default # Set to storage being used
    accessMode: ReadWriteOnce
    size: 100Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 0.1
    limits:
      memory: 16Gi
      cpu: 8
  config:
    http:
      bind_address: 8086

mysql:
  imageTag: "5.6"
  imagePullPolicy: IfNotPresent
  persistence:
    enabled: false
    storageClass: default
    accessMode: ReadWriteOnce
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m
  mysqlRootPassword: secretmysql
  users:
    api:
      username: monapi
      password: password
    notification:
      username: notification
      password: password
    thresh:
      username: thresh
      password: password
    keystone:
      username: keystone
      password: keystone

agent:
  name: agent
  image:
    repository: monasca/agent
    tag: latest
    pullPolicy: Always
  log_level: WARN
  insecure: False
  keystone:
    os_username: mini-mon
    os_user_domain_name: Default
    os_password: password
    os_project_name: mini-mon
    os_project_domain_name: Default
  prometheus:
    auto_detect_pod_endpoints: true
    auto_detect_service_endpoints: true
    kubernetes_labels: 'app'
    timeout: 3
  kubernetes_api:
    kubernetes_labels: 'app'
    timeout: 3
    storage:
      report: true
  kubernetes:
    kubernetes_labels: 'app'
    timeout: 3
  cadvisor:
    enabled: true
    timeout: 3
  proxies:
    http: ''
    https: ''
    no_proxy: ''
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

api:
  name: api
  image:
    repository: monasca/api
    tag: master-prometheus
    pullPolicy: Always
  replicaCount: 1
  keystone:
    admin_password: secretadmin
    admin_user: admin
    admin_tenant: admin
  influxdb:
    user: mon_api
    password: password
    database: mon
  service:
    port: 8070
    type: ClusterIP
  logging:
    log_level_root: WARN
    log_level_console: WARN
  auth_disabled: false
  side_container:
    enabled: true
    image:
      repository: timothyb89/monasca-sidecar
      tag: 1.0.0
      pullPolicy: Always
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 100m
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 2000m

forwarder:
  name: forwarder
  enabled: false
  image:
    repository: monasca/forwarder
    tag: master
    pullPolicy: Always
  insecure: False
  replicaCount: 1
  logging:
    debug: false
    verbose: true
  config:
    remote_api_url: http://monasca:8070/v2.0
    monasca_project_id: 3564760a3dd44ae9bd6618d442fd758c
    use_insecure: false
    monasca_role: monasca-agent
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 100m
  proxies:
    http: ''
    https: ''
    no_proxy: ''
  metric_configuration:
    forwarder_metric_match.yml: |
      metrics_to_forward:
        - name: kubernetes.node.allocatable.cpu_agg
        - name: cpu.total_time_sec_agg

grafana:
  name: grafana
  image:
    repository: monasca/grafana
    tag: 4.0.0-1.1.0
    pullPolicy: Always
  service:
    type: NodePort
    port: 3000
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m
  proxies:
    http: ''
    https: ''
    no_proxy: ''

keystone:
  name: keystone
  bootstrap:
    user: admin
    password: secretadmin
    project: admin
    role: admin
    service: keystone
    region: RegionOne
  database_backend: mysql
  image:
    pullPolicy: Always
    tag: 1.1.0
    repository: monasca/keystone
  mysql:
    database: keystone
  replicaCount: 1
  service:
    type: ClusterIP
    port: 35357
    admin_port: 5000
  users:
    mini_mon:
      password: password
    monasca_agent:
      password: password
    admin:
      password: secretadmin
    demo:
      password: secretadmin
    monasca_read_only:
      password: password
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m

notification:
  name: notification
  image:
    repository: monasca/notification
    tag: master
    pullPolicy: Always
  replicaCount: 1
  log_level: WARN
  plugins: pagerduty,webhook
  plugin_config:
    email:
      defined: false
    webhook:
      timeout: 5
    slack:
      timeout: 5
    hipchat:
      timeout: 5
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 500m

persister:
  name: persister
  image:
    repository: monasca/persister
    tag: master
    pullPolicy: Always
  replicaCount: 1
  influxdb:
    user: mon_persister
    password: password
    database: mon
  logging:
    debug: false
    verbose: true
  kafka:
    metrics:
      batch_size: 1000
      wait_time: 15
    alarm_history:
      batch_size: 1000
      wait_time: 15
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 100m

storm:
  name: storm
  image:
    repository: monasca/storm
    tag: 1.0.3
    pullPolicy: Always
  persistence:
    storageClass: default
    enabled: false
    accessMode: ReadWriteOnce
    size: 4Gi
  service:
    type: ClusterIP
    port: 6627
  nimbus_resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 2Gi
      cpu: 500m
  supervisor_resources:
    requests:
      memory: 2Gi
      cpu: 250m
    limits:
      memory: 4Gi
      cpu: 2000m

thresh:
  name: thresh
  image:
    repository: monasca/thresh
    tag: master
    pullPolicy: Always
  secretSuffix: mysql-thresh-secret
  spout:
    metricSpoutThreads: 2
    metricSpoutTasks: 2
  wait:
    retries: 24
    delay: 5
    timeout: 10

client:
  name: client
  enabled: false
  image:
    repository: rbrndt/python-monascaclient
    tag: latest
    pullPolicy: Always
  keystone:
    os_username: mini-mon
    os_user_domain_name: Default
    os_password: password
    os_project_name: mini-mon
    os_project_domain_name: Default

rbac:
  enabled: false

kafka:
  service:
    port: 9092
  zookeeper:
    service:
      port: 2181

cleanup:
  name: cleanup
  image:
    repository: monasca/job-cleanup
    tag: 1.1.0
    pullPolicy: IfNotPresent
