apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "grafana.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.grafana.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: "{{ .Values.grafana.name }}"
    spec:
      containers:
        - name: {{ template "name" . }}-{{ .Values.grafana.name }}
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          resources:
{{ toYaml .Values.grafana.resources | indent 12 }}
          env:
            {{- if .Values.grafana.proxies.https }}
            - name: HTTPS_PROXY
              value: {{ .Values.grafana.proxies.https | quote }}
            - name: https_proxy
              value: {{ .Values.grafana.proxies.https | quote }}
            {{- end}}
            {{- if .Values.grafana.proxies.http }}
            - name: HTTP_PROXY
              value: {{ .Values.grafana.proxies.http | quote }}
            - name: http_proxy
              value: {{ .Values.grafana.proxies.http | quote }}
            {{- end}}
            {{- if .Values.grafana.proxies.no_proxy }}
            - name: NO_PROXY
              value: {{ .Values.grafana.proxies.no_proxy | quote }}
            - name: no_proxy
              value: {{ .Values.grafana.proxies.no_proxy | quote }}
            {{- end}}
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
          - name: grafana-config
            mountPath: /etc/grafana
      volumes:
        - name: grafana-config
          configMap:
            name: {{ template "grafana.fullname" . }}
